const videos = [
  {
    id: 1,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video. Talking about tech, AI, and more."
  },
  {
    id: 2,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video. Talking about tech, AI, and more."
  },
  {
    id: 3,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 4,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  },
  {
    id: 5,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video."
  },
  {
    id: 6,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "Funny moments compilation."
  },
  {
    id: 7,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 8,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  },
  {
    id: 9,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video."
  },
  {
    id: 10,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "Funny moments compilation."
  },
  {
    id: 11,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 12,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  },
  {
    id: 13,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video."
  },
  {
    id: 14,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "Funny moments compilation."
  },
  {
    id: 15,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 16,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  },
  {
    id: 17,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video."
  },
  {
    id: 18,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "Funny moments compilation."
  },
  {
    id: 19,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 20,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  },
  {
    id: 21,
    title: "Talking Tech and AI with Google CEO Sundar Pichai!",
    videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY&themeRefresh=1",
    author: "Marques Brownlee",
    views: "3.4M views",
    time: "14:20",
    thumbnail: "assets/thumbnails/thumbnail-1.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "6 months ago",
    description: "This is a sample description of the video."
  },
  {
    id: 22,
    title: "Try Not To Laugh Challenge #9",
    videoLink: "https://youtu.be/mP0RAo9SKZk?si=83j-DrX4tLy6206t",
    author: "Markiplier",
    views: "19M views",
    time: "8:22",
    thumbnail: "assets/thumbnails/thumbnail-2.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "Funny moments compilation."
  },
  {
    id: 23,
    title: "New Troop & Defense Levels - Update Sneak Peek!",
    videoLink: "https://youtu.be/3nnL5Bk1z14?si=bo7nTDW_2lDySxwz",
    author: "Judo Sloth Gaming",
    views: "338K views",
    time: "21:20",
    thumbnail: "assets/thumbnails/thumbnail coc.jfif",
    channelImg: "assets/images/channel-1.jpeg",
    date: "19 hours ago",
    description: "Learn about the latest troop and defense levels in this sneak peek update!"
  },
  {
    id: 24,
    title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
    videoLink: "https://youtu.be/094y1Z2wpJg?si=MeEsdBZISvb5hd8F",
    author: "Veritasium",
    views: "45M views",
    time: "22:09",
    thumbnail: "assets/thumbnails/thumbnail-4.webp",
    channelImg: "assets/images/channel-1.jpeg",
    date: "4 years ago",
    description: "The Collatz Conjecture is a simple yet unsolved problem in mathematics."
  }
];

function openYouTubeVideo(link) {
  window.open(link, '_blank');
}